from config import MQTT_APPS_BASE

I2C_ADDR = 41

MQTT_POTTYBOX_BASE = f"{MQTT_APPS_BASE}/pottybox"
MQTT_TOPIC_DUAL_POTTY = f"{MQTT_POTTYBOX_BASE}/config/dual_potty"
MQTT_TOPIC_EXHAUST_TIME = f"{MQTT_POTTYBOX_BASE}/config/exhaust_time"
